version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./budgetapi/:/home/budgetapi/budgetapi
    command: >
      sh -c "
            poetry run python manage.py makemigrations
            poetry run python manage.py migrate &&
            poetry run python manage.py ensure_superuser \
              --username ${BUDGETAPI_SUPERUSER_USERNAME:-root} \
              --password ${BUDGETAPI_SUPERUSER_PASSWORD:-root} \
              --email ${BUDGETAPI_SUPERUSER_EMAIL:-root@example.com} &&
            poetry run python manage.py collectstatic --no-input &&
            poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - postgres
  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: celery
    volumes:
      - ./budgetapi/:/home/budgetapi/budgetapi
    command: celery -A celeryapp worker -l info
    depends_on:
      - redis
      - api
  celerybeat:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: celerybeat
    volumes:
      - ./budgetapi/:/home/budgetapi/budgetapi
    command: celery -A celeryapp beat -l info
    tty: true  # persist (should use 'sh' as entrypoint)
    depends_on:
      - redis
      - api
  redis:
    image: redis:7.0.5-alpine
    container_name: redis
  flower:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flower
    command:  celery --broker=redis://redis:6379/0 -A celeryapp flower --port=5555
    ports:
      - 5555:5555
    depends_on:
      - api
      - redis
      - celery
  postgres:
      image: postgres:15.1
      container_name: postgres
      environment:
        - POSTGRES_PASSWORD=${BUDGETAPI_POSTGRES_PASSWORD:-budgetapi}
        - POSTGRES_DB=${BUDGETAPI_POSTGRES_DB:-budgetapi}
        - POSTGRES_USER=${BUDGETAPI_POSTGRES_USER:-budgetapi}
      restart: always
      ports:
        - ${BUDGETAPI_POSTGRES_PORT:-5432}:${BUDGETAPI_POSTGRES_PORT:-5432}
      volumes:
        - ./.postgresdata:/var/lib/postgresql/data